# Generated by Django 6.0.1 on 2026-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='newemail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
