# Generated by Django 6.0.1 on 2026-02-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
